### PR TITLE
add video read and a condition for empty pixels

### PR DESCRIPTION
**Pull request by micuat**
tested with processing 3.5.4

### CODE REVIEW

**Comment by ffd8** [comment]
Thanks for the PR – I hadn't run into this issue at all (MacOS 10.13.6 and lower), also tried running without a camera attached (laptop closed), where I just get a gray 'nothing' screen, but no crash... maybe on Windows/Linux it crashes? Happy to merge.. though I wonder if it also needs the additional lines as mentioned in the [Capture ref](https://processing.org/reference/libraries/video/Capture.html):

```
if (video.available() == true) {
  video.read();
}
```

... technically shouldn't the whole video to pixel reading operation be surrounded by that, so it can only try to loadPixels etc if it was available?

**Comment by micuat** [comment]
thanks. I'm on windows 10. I just updated the code - actually I first tried similar to what you suggested but instead,

```processing
if (video.available() == false) {
  return;
}
```

but did not work so I did a workaround with `video.pixels.length == 0` - however I just tried something nicer (the updated PR) and it seems working fine.

**Comment by ffd8** [comment]
Small tweak – I don't think so much code needs to be wrapped (since the openCV/Xyscope stuff can take place on a blank p image if no video is available.. should only need to wrap the grabbing of video, loading of pixels, and updating of p image:

~ lines 69 - 80
```
if (video.available() == true) {
  // convert video to high contrast threshold
  video.loadPixels();
  for (int i=0; i<p.width*p.height; i++) {
    if (brightness(video.pixels[i]) > threshold && brightness(video.pixels[i]) < threshold+thresholdDist) {
      p.pixels[i]  = color(0); // White
    } else {
      p.pixels[i]  = color(255); // Black
    }
  }
  p.updatePixels();
}
```

**Comment by micuat** [comment]
done - `video.read()` was needed anyways (at least on windows)

**Comment by ffd8** [comment]
Good to know it's needed on Windows + thanks for the PR!

**Pull request merged**
